version: '3.8'


services:
  redis:
    image: redis:alpine3.18
    container_name: redisc
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
  postgres-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432