app: culqui-lambda
service: culqui-lambda
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x

functions:
  createToken:
    handler: src/handlers/card.createCard
    events:
      - httpApi:
          path: /api/token
          method: post
  findCardbyToken:
    handler: src/handlers/card.findCardByToken
    events:
      - httpApi:
          path: /api/token/{id}
          method: get
plugins:
  - serverless-plugin-typescript
  - serverless-offline
