org: marvolov
app: typescript-http-api
service: typescript-http-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x

functions:
  createToken:
    handler: src/handlers/card.createCard
    events:
      - httpApi:
          path: /token
          method: post
  findCardbyToken:
    handler: src/handlers/card.findCardByToken
    events:
      - httpApi:
          path: /token/{id}
          method: get
plugins:
  - serverless-plugin-typescript
  - serverless-offline
